services:
  - type: web
    name: mk-event-server
    runtime: node
    rootDir: server
    buildCommand: npm install --omit=dev
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        value: https://mkbrothers.netlify.app
      - key: NODE_ENV
        value: production
